targets:
  $default:
    builders:
      is_getters_generator|is_getters|has_getter_generator|has_getter:
        enabled: true

builders:
  is_getters:
    target: ":is_getters_generator"
    import: "package:has_is_getters_generator/is_getters_generator.dart"
    builder_factories: ["generateIsGetters"]
    build_extensions: { ".dart": [".is_getters.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  has_getters:
    target: ":has_getter_generator"
    import: "package:has_is_getters_generator/has_getter_generator.dart"
    builder_factories: ["generateHasGetter"]
    build_extensions: { ".dart": [".has_getter.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
