name: has_is_getters_generator
version: 0.0.1
author: Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/marcelgarus/has_is_getters

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  analyzer: ">=0.27.1 <1.0.0"
  build: ">=0.12.0 <2.0.0"
  has_is_getters:
    path: ../has_is_getters
  source_gen: ^0.9.0

dev_dependencies:
  build_runner: ">=0.9.0 <1.6.7"
