name: has_is_getters_generator
description: Annotations for generating getters for checking whether a field is null or checking the value of a field.
version: 1.1.0
author: Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/marcelgarus/has_is_getters

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  analyzer: ">=0.27.1 <1.0.0"
  build: ">=0.12.0 <2.0.0"
  has_is_getters: ^1.1.0
  source_gen: ^0.9.0

dev_dependencies:
  build_runner: ">=0.9.0 <1.6.7"
